# frozen_string_literal: true

source "https://rubygems.org"

gem "capybara"
gem "cucumber", "~> 3.2.0"
gem "cpf_faker"
gem "faker"
gem "ffi"
gem "report_builder"
gem "rspec"
gem "rufo"
gem "solargraph"
gem "rubocop"
gem "selenium-webdriver"
